# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shipping_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('urlh', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('crawl_time', models.DateTimeField(blank=True, null=True)),
                ('crawl_date', models.DateField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, null=True)),
                ('available_price', models.FloatField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('stock', models.CharField(blank=True, max_length=50, null=True)),
                ('variant', models.CharField(blank=True, max_length=1000, null=True)),
                ('offers', models.CharField(blank=True, max_length=1000, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=1000, null=True)),
                ('sku', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_change', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('timestamp', models.DateTimeField()),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('cashback', models.CharField(blank=True, max_length=1000, null=True)),
                ('shipping_charges', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('warranty', models.CharField(blank=True, max_length=500, null=True)),
                ('seller', models.CharField(blank=True, max_length=500, null=True)),
                ('others', models.TextField(blank=True, null=True)),
                ('meta', models.CharField(blank=True, max_length=1500, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
    ]
